project:
  type: website
  preview:
    port: 4202
execute:
  freeze: true

website:
  back-to-top-navigation: true
  page-navigation: true
  image: "preview.png"
  title: "Mimansa Jaiswal"
  description: "I am actively seeking industry research scientist and engineering positions in model evaluation, metric design, model explanation, and interpretation, and, work at the intersection of LLMs and productivity intermixed with design."
  favicon: favicon.ico
  site-url: https://mimansajaiswal.github.io
  google-analytics: UA-129147840-1
  open-graph:
    title: "Mimansa Jaiswal"
    image: "preview.png"
    description: "I am actively seeking industry research scientist and engineering positions in model evaluation, metric design, model explanation, and interpretation, and, work at the intersection of LLMs and productivity intermixed with design."
  twitter-card:
    creator: "@MimansaJ"
    site: "@MimansaJ"
    image: "preview.png"
    description: "I am actively seeking industry research scientist and engineering positions in model evaluation, metric design, model explanation, and interpretation, and, work at the intersection of LLMs and productivity intermixed with design."

  navbar:
    background: dark
    title: Home
    pinned: true
    collapse: true
    search: true
    left:
      - icon: newspaper
        href: single_page/updates.qmd
      - icon: pen-fill
        href: single_page/papers.qmd
      - icon: text-indent-left
        href: notes/index.qmd
      # - icon: cursor-text
      #   href: stream/index.qmd
      - icon: cursor-text
        href: single_page/blurbs.qmd
    right:
      - icon: twitter
        text: Twitter
        href: https://twitter.com/MimansaJ
      - icon: rss
        text: Feed
        href: notes/index.xml

format:
  html:
    # theme: sketchy
    smooth-scroll: true
    theme: quarto_mod.scss
    highlight-style: quarto_mod.theme
    metadata:
      pagetitle: "{{< meta title >}}"
      freeze: true
      title-block-banner: false
      author: Mimansa Jaiswal
      title-block-categories: true
      toc-depth: 7

comments:
  giscus: 
    repo: mimansajaiswal/mimansajaiswal.github.io
    repo-id: R_kgDOJo-RfQ
    category: Announcements
    category-id: DIC_kwDOJo-Rfc4CW3WB
    mapping: pathname
    loading: lazy
    input-position: top
    reactions-enabled: true
  
  hypothesis:
    theme: clean
    openSidebar: false
    showHighlights: whenSidebarOpen