project:
  type: website
  preview:
    port: 4202
execute:
  freeze: true

website:
  open-graph: true
  back-to-top-navigation: true
  page-navigation: true
  twitter-card:
    creator: "@MimansaJ"
    site: "@MimansaJ"
  title: "Mimansa Jaiswal"
  favicon: favicon.ico
  site-url: https://mimansajaiswal.github.io

  navbar:
    background: dark
    pinned: true
    collapse: true
    search: true
    left:
      - icon: newspaper
        href: single_page/news.qmd
      - icon: postcard
        href: single_page/papers.qmd
      - icon: folder2
        href: single_page/projects.qmd
      - icon: text-indent-left
        href: posts/index.qmd
      - icon: cursor-text
        href: stream/index.qmd
    right:
      - icon: twitter
        text: Twitter
        href: https://twitter.com/MimansaJ
      - icon: rss
        text: Feed
        href: posts/index.xml

format:
  html:
    # theme: sketchy
    theme: quarto_mod.scss
    highlight-style: quarto_mod.theme
    include-in-header: [analytics-head.html]
    # include-after-body: [analytics-body.html]
    metadata:
      pagetitle: "{{< meta title >}}"
      freeze: true
      title-block-banner: false
      author: Mimansa Jaiswal
      title-block-categories: true
      toc-depth: 5

comments:
  giscus: 
    repo: mimansajaiswal/mimansajaiswal-new.github.io
    repo-id: R_kgDOJo-RfQ
    category: Announcements
    category-id: DIC_kwDOJo-Rfc4CW3WB
    mapping: pathname
    loading: lazy
    input-position: top
    reactions-enabled: true
  
  hypothesis:
    theme: clean
    openSidebar: false
    showHighlights: whenSidebarOpen